services:
  api:
    container_name: gitcord_api
    image: ghcr.io/ijskoud/gitcord:api
    restart: always

    env_file:
      - ~/gitcord/.env
    ports:
      - 3001:3000

  bot:
    container_name: gitcord_bot
    image: ghcr.io/ijskoud/gitcord:bot
    restart: always

    env_file:
      - ~/gitcord/.env
